name: 'Generate component labels'
on:
  schedule:
    - cron: "55 2 * * 1-5" # Run at a random time on weekdays
  workflow_dispatch:

jobs:
  generate-component-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate component labels
        run: ./.github/workflows/scripts/generate-component-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

