name: 'Generate component labels'
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate-component-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate component labels
        run: git diff --quiet HEAD~ HEAD -- .github/CODEOWNERS || ./.github/workflows/scripts/generate-component-labels.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

